---
- name: Get latest release number
  uri:
    url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
    return_content: yes
  register: kubectl_release

- name: Print release number
  debug:
    msg: "Installing Kubectl latest version {{ kubectl_release.content }}"

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_release.content }}/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: "+x"
